name: MR CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - run: npm ci
      - run: npm run lint
      - run: npm test
  version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG_EXISTS=$(git tag -l "v$VERSION")

          if [[ "$TAG_EXISTS" == "v$VERSION" ]]; then
            echo "Tag already exists for version $VERSION. Please update the version in package.json."
            exit 1
          else
            echo "No existing tag found for version $VERSION. Proceeding with the workflow."
          fi